name: monitoring
title: Monitoring
type: infrastructure
hostname: monitoring
containers:
- name: alloy

helm:
  name: grafana
  source: https://grafana.github.io/helm-charts
  chart: grafana/k8s-monitoring
  version: 1.0.1
  configurations:
  - name: alloy
    resources: alloy.resources
    env: alloy.extraEnv
    labels: alloy.labels
    annotations: alloy.controller.extraAnnotations
  values:
  - name: cluster.name
    value: '{{kubernetes.id}}'
  - name: externalServices.prometheus.host
    value: '{{wodby_agent_metrics_endpoint}}'
  - name: externalServices.prometheus.basicAuth.username
    value: '{{wodby_agent_username}}'
  - name: externalServices.prometheus.basicAuth.password
    value: '{{wodby_agent_password}}'
  - name: externalServices.prometheus.tenantId
    value: '{{org.id}}'
  - name: externalServices.prometheus.writeEndpoint	
    value: ""
  - name: alloy.fullnameOverride
    value: '{{service.name}}'
  - name: opencost.enabled
    value: false
  - name: cost.enabled
    value: false
  - name: logs.enabled
    value: false
  - name: logs.pod_logs.enabled
    value: false
  - name: logs.cluster_events.enabled
    value: false
  - name: receivers.grpc.enabled
    value: false
  - name: receivers.http.enabled
    value: false
  - name: prometheus-operator-crds.enabled
    value: false
  - name: metrics.podMonitors.enabled
    value: false
  - name: metrics.probes.enabled
    value: false
  - name: metrics.serviceMonitors.enabled
    value: false
  - name: metrics.probes.enabled
    value: false
  - name: metrics.cost.enabled
    value: false
  - name: kube-state-metrics.enabled
    value: false
  - name: prometheus-node-exporter.enabled
    value: false
  - name: metrics.node-exporter.metricsTuning.includeMetrics
    value: 
    - node_cpu.*
    - node_exporter_build_info
    - node_filesystem.*
    - node_memory.*
    - process_cpu_seconds_total
    - process_resident_memory_bytes
    - node_load1
    - node_load15
    - node_load5
  - name: metrics.cadvisor.metricsTuning.includeMetrics
    value: 
    - container_cpu_cfs_periods_total
    - container_cpu_cfs_throttled_periods_total
    - container_cpu_usage_seconds_total
    - container_fs_reads_bytes_total
    - container_fs_reads_total
    - container_fs_writes_bytes_total
    - container_fs_writes_total
    - container_memory_cache
    - container_memory_rss
    - container_memory_swap
    - container_memory_working_set_bytes
    - container_network_receive_bytes_total
    - container_network_receive_packets_dropped_total
    - container_network_receive_packets_total
    - container_network_transmit_bytes_total
    - container_network_transmit_packets_dropped_total
    - container_network_transmit_packets_total
    - machine_memory_bytes    
    - machine_cpu_cores
